#!/bin/bash

#FILES="$(ls assets/gallery/**/*.JPG | sed '/^[[:space:]]*$/d')"
FILES="https://i.ibb.co/WFnGdM6/coldaciddetergent.jpg
https://i.ibb.co/wdWL02y/coldacid.jpg
https://i.ibb.co/NjR1yV0/coldacidsalt.jpg
https://i.ibb.co/SvWZrf9/coldacidvinegar.jpg
https://i.ibb.co/TH0StY5/colddisperse.jpg
https://i.ibb.co/1vnhZdM/colddispersedetergent.jpg
https://i.ibb.co/3MNFYsM/colddispersesalt.jpg
https://i.ibb.co/Yt6mP0V/colddispersevinegar.jpg
https://i.ibb.co/1TJD2gd/coldink.jpg
https://i.ibb.co/nM8qLFH/coldinkdetergent.jpg
https://i.ibb.co/svC5yKK/coldinksalt.jpg
https://i.ibb.co/26cz8WT/coldinkvinegar.jpg
https://i.ibb.co/gPgKhSP/coldreactive.jpg
https://i.ibb.co/QdB4s0B/coldreactivedetergent.jpg
https://i.ibb.co/nrFmPth/coldreactivesalt.jpg
https://i.ibb.co/5vMLpYW/coldreactivevinegar.jpg
https://i.ibb.co/PjSydGL/hotacid.jpg
https://i.ibb.co/HYYkSkJ/hotaciddetergent.jpg
https://i.ibb.co/2Z07sZ5/hotacidsalt.jpg
https://i.ibb.co/9npvz3g/hotacidvinegar.jpg
https://i.ibb.co/hdXZqNM/hotdisperse.jpg
https://i.ibb.co/JzyZ0Fz/hotdispersedetergent.jpg
https://i.ibb.co/DYz66qw/hotdispersesalt.jpg
https://i.ibb.co/Lt6sCrf/hotdispersevinegar.jpg
https://i.ibb.co/PTPPZW1/hotink.jpg
https://i.ibb.co/mJX8Lb5/hotinkdetergent.jpg
https://i.ibb.co/Wc0xw5Z/hotinksalt.jpg
https://i.ibb.co/nC0ywBT/hotinkvinegar.jpg
https://i.ibb.co/rtxV7qJ/hotreactive.jpg
https://i.ibb.co/QjKpFqS/hotreactivedetergent.jpg
https://i.ibb.co/nM3KN6v/hotreactivesalt.jpg
https://i.ibb.co/vJ6QS1h/hotreactivevinegar.jpg
https://i.ibb.co/PG8rNpQ/coldaciddetergent.jpg
https://i.ibb.co/vBzDhcY/coldacid.jpg
https://i.ibb.co/41K0sqh/coldacidsalt.jpg
https://i.ibb.co/hZmqXCX/coldacidvinegar.jpg
https://i.ibb.co/CbV1YX8/colddisperse.jpg
https://i.ibb.co/NxdKWDm/colddispersedetergent.jpg
https://i.ibb.co/x739Dvj/colddispersesalt.jpg
https://i.ibb.co/mF8mmv3/colddispersevinegar.jpg
https://i.ibb.co/L92VM5F/coldink.jpg
https://i.ibb.co/9NjPZqw/coldinkdetergent.jpg
https://i.ibb.co/C5JSL2q/coldinksalt.jpg
https://i.ibb.co/P1gXfFJ/coldinkvinegar.jpg
https://i.ibb.co/QMjXrfy/coldreactive.jpg
https://i.ibb.co/SmGvLjF/coldreactivedetergent.jpg
https://i.ibb.co/rmyQ69p/coldreactivesalt.jpg
https://i.ibb.co/k9trPfj/coldreactivevinegar.jpg
https://i.ibb.co/TKB6Ykt/hotacid.jpg
https://i.ibb.co/Wgf4n9c/hotaciddetergent.jpg
https://i.ibb.co/ZmsBhK8/hotacidsalt.jpg
https://i.ibb.co/MMDrWHQ/hotacidvinegar.jpg
https://i.ibb.co/wL5rWtL/hotdisperse.jpg
https://i.ibb.co/4mV27g9/hotdispersedetergent.jpg
https://i.ibb.co/svTvSSS/hotdispersesalt.jpg
https://i.ibb.co/j5Qmxv8/hotdispersevinegar.jpg
https://i.ibb.co/6Fr74b1/hotink.jpg
https://i.ibb.co/JKLYgNq/hotinkdetergent.jpg
https://i.ibb.co/Nmf5n7h/hotinksalt.jpg
https://i.ibb.co/qpXymp3/hotinkvinegar.jpg
https://i.ibb.co/WK6TRw8/hotreactive.jpg
https://i.ibb.co/Q6XvZ1B/hotreactivedetergent.jpg
https://i.ibb.co/86KWscf/hotreactivesalt.jpg
https://i.ibb.co/Km6xxBt/hotreactivevinegar.jpg
https://i.ibb.co/F0VS8hZ/coldaciddetergent.jpg
https://i.ibb.co/JjHbXLx/coldacid.jpg
https://i.ibb.co/s9vNgy2/coldacidsalt.jpg
https://i.ibb.co/Z25spY5/coldacidvinegar.jpg
https://i.ibb.co/dMFv948/colddisperse.jpg
https://i.ibb.co/r58s9DX/colddispersedetergent.jpg
https://i.ibb.co/wZHzFY6/colddispersesalt.jpg
https://i.ibb.co/Gc1hjsk/colddispersevinegar.jpg
https://i.ibb.co/JvdZJYS/coldink.jpg
https://i.ibb.co/sWQJnPj/coldinkdetergent.jpg
https://i.ibb.co/r5mfFfL/coldinksalt.jpg
https://i.ibb.co/khV3nDV/coldinkvinegar.jpg
https://i.ibb.co/gRTqcCd/coldreactive.jpg
https://i.ibb.co/sbxsG4B/coldreactivedetergent.jpg
https://i.ibb.co/sP4QVHF/coldreactivesalt.jpg
https://i.ibb.co/tZ9nnd6/coldreactivevinegar.jpg
https://i.ibb.co/8K3NMgx/hotacid.jpg
https://i.ibb.co/xD38Jr5/hotaciddetergent.jpg
https://i.ibb.co/vJ1MZBk/hotacidsalt.jpg
https://i.ibb.co/Qr4SFbr/hotacidvinegar.jpg
https://i.ibb.co/FnvV0Wc/hotdisperse.jpg
https://i.ibb.co/8BMHcGT/hotdispersedetergent.jpg
https://i.ibb.co/7RrCMp6/hotdispersesalt.jpg
https://i.ibb.co/56bMvJ1/hotdispersevinegar.jpg
https://i.ibb.co/SQghpTV/hotink.jpg
https://i.ibb.co/t3ZwNYW/hotinkdetergent.jpg
https://i.ibb.co/hB0QD61/hotinksalt.jpg
https://i.ibb.co/ZdCw58h/hotinkvinegar.jpg
https://i.ibb.co/tDKvVt4/hotreactive.jpg
https://i.ibb.co/gZCcZnq/hotreactivedetergent.jpg
https://i.ibb.co/jfyNtkD/hotreactivesalt.jpg
https://i.ibb.co/Yf0t5Hp/hotreactivevinegar.jpg
https://i.ibb.co/DkKnrcR/coldaciddetergent.jpg
https://i.ibb.co/YQRgzdR/coldacid.jpg
https://i.ibb.co/cFxt0VM/coldacidsalt.jpg
https://i.ibb.co/wp61tgf/coldacidvinegar.jpg
https://i.ibb.co/DMN6rLB/colddisperse.jpg
https://i.ibb.co/FzrtyjV/colddispersedetergent.jpg
https://i.ibb.co/5TtN0ZJ/colddispersesalt.jpg
https://i.ibb.co/djknJtJ/colddispersevinegar.jpg
https://i.ibb.co/QbZZRwf/coldink.jpg
https://i.ibb.co/CBgx1fQ/coldinkdetergent.jpg
https://i.ibb.co/j5JNfdz/coldinksalt.jpg
https://i.ibb.co/4mG8nLH/coldinkvinegar.jpg
https://i.ibb.co/Dr0nHsS/coldreactive.jpg
https://i.ibb.co/bvwKDyP/coldreactivedetergent.jpg
https://i.ibb.co/2PSY4tX/coldreactivesalt.jpg
https://i.ibb.co/KLQQy1j/coldreactivevinegar.jpg
https://i.ibb.co/qJP8HCk/hotacid.jpg
https://i.ibb.co/254x8sV/hotaciddetergent.jpg
https://i.ibb.co/hDCJJNq/hotacidsalt.jpg
https://i.ibb.co/NNTTdZ7/hotacidvinegar.jpg
https://i.ibb.co/tpQnypP/hotdisperse.jpg
https://i.ibb.co/YRpXk41/hotdispersedetergent.jpg
https://i.ibb.co/nmZW46r/hotdispersesalt.jpg
https://i.ibb.co/pXXn0Xv/hotdispersevinegar.jpg
https://i.ibb.co/hM5365N/hotink.jpg
https://i.ibb.co/VmqxY10/hotinkdetergent.jpg
https://i.ibb.co/pzLQ4db/hotinksalt.jpg
https://i.ibb.co/nQZ2j52/hotinkvinegar.jpg
https://i.ibb.co/HVFYDpM/hotreactive.jpg
https://i.ibb.co/BsftgHz/hotreactivedetergent.jpg
https://i.ibb.co/k5fDL93/hotreactivesalt.jpg
https://i.ibb.co/hWFfM63/hotreactivevinegar.jpg
https://i.ibb.co/rx0mH90/coldaciddetergent.jpg
https://i.ibb.co/NCkkK5r/coldacid.jpg
https://i.ibb.co/rttGrjc/coldacidsalt.jpg
https://i.ibb.co/KNDKD5k/coldacidvinegar.jpg
https://i.ibb.co/yypjLLr/colddisperse.jpg
https://i.ibb.co/qYXrR5B/colddispersedetergent.jpg
https://i.ibb.co/jGmVBSH/colddispersesalt.jpg
https://i.ibb.co/XsPpRyX/colddispersevinegar.jpg
https://i.ibb.co/ByHDbYg/coldink.jpg
https://i.ibb.co/5jXrpLn/coldinkdetergent.jpg
https://i.ibb.co/wRBTMy7/coldinksalt.jpg
https://i.ibb.co/HNRLhtQ/coldinkvinegar.jpg
https://i.ibb.co/hB1G25m/coldreactive.jpg
https://i.ibb.co/8YNgm5h/coldreactivedetergent.jpg
https://i.ibb.co/C1XrvKF/coldreactivesalt.jpg
https://i.ibb.co/S7wPs09/coldreactivevinegar.jpg
https://i.ibb.co/1fBfTR9/hotacid.jpg
https://i.ibb.co/bK2r5dF/hotaciddetergent.jpg
https://i.ibb.co/5MCdRFz/hotacidsalt.jpg
https://i.ibb.co/djLQQNr/hotacidvinegar.jpg
https://i.ibb.co/9WDrsdK/hotdisperse.jpg
https://i.ibb.co/cD1bw7F/hotdispersedetergent.jpg
https://i.ibb.co/tbb1VWp/hotdispersesalt.jpg
https://i.ibb.co/bFKQf6R/hotdispersevinegar.jpg
https://i.ibb.co/d0m6FG2/hotink.jpg
https://i.ibb.co/ScXN8YX/hotinkdetergent.jpg
https://i.ibb.co/yPtq7Kf/hotinksalt.jpg
https://i.ibb.co/wMj1th6/hotinkvinegar.jpg
https://i.ibb.co/25jYKdc/hotreactive.jpg
https://i.ibb.co/z2W5XkF/hotreactivedetergent.jpg
https://i.ibb.co/WKJryfh/hotreactivesalt.jpg
https://i.ibb.co/zhQcYN9/hotreactivevinegar.jpg
https://i.ibb.co/f1qjNbL/coldaciddetergent.jpg
https://i.ibb.co/MGqjKpv/coldacid.jpg
https://i.ibb.co/wpS5dkd/coldacidsalt.jpg
https://i.ibb.co/GtZfzbW/coldacidvinegar.jpg
https://i.ibb.co/MSCfkN1/colddisperse.jpg
https://i.ibb.co/H2PVVV5/colddispersedetergent.jpg
https://i.ibb.co/tQXL674/colddispersevinegar.jpg
https://i.ibb.co/ZLnFWrR/coldink.jpg
https://i.ibb.co/k1wwWL2/coldinkdetergent.jpg
https://i.ibb.co/C8jcsxC/coldinksalt.jpg
https://i.ibb.co/jbJ4wSX/coldinkvinegar.jpg
https://i.ibb.co/R6s7Kv0/coldispersesalt.jpg
https://i.ibb.co/c6MNCvB/coldreactive.jpg
https://i.ibb.co/HtcFBnF/coldreactivedetergent.jpg
https://i.ibb.co/2yW8DVR/coldreactivesalt.jpg
https://i.ibb.co/Wn1qkH4/coldreactivevinegar.jpg
https://i.ibb.co/hHSxZMj/hotacid.jpg
https://i.ibb.co/4fm672b/hotaciddetergent.jpg
https://i.ibb.co/B4L88dZ/hotacidsalt.jpg
https://i.ibb.co/PN2Tbcf/hotacidvinegar.jpg
https://i.ibb.co/Nt2kcn7/hotdisperse.jpg
https://i.ibb.co/T4sztZM/hotdispersedetergent.jpg
https://i.ibb.co/WzcmvNH/hotdispersesalt.jpg
https://i.ibb.co/jGrM6st/hotdispersevinegar.jpg
https://i.ibb.co/DDhphCx/hotink.jpg
https://i.ibb.co/NFBr80q/hotinkdetergent.jpg
https://i.ibb.co/qxMxVh5/hotinksalt.jpg
https://i.ibb.co/RYy6Cjc/hotinkvinegar.jpg
https://i.ibb.co/N1cKnwz/hotreactive.jpg
https://i.ibb.co/ky8K9k6/hotreactivedetergent.jpg
https://i.ibb.co/8Kj3VVF/hotreactivesalt.jpg
https://i.ibb.co/Y3Hyq9m/hotreactivevinegar.jpg
https://i.ibb.co/PWhRv42/coldacid.jpg
https://i.ibb.co/LP67CHN/coldaciddetergent.jpg
https://i.ibb.co/FYnrQnK/coldacidsalt.jpg
https://i.ibb.co/CwxCKhd/coldacidvinegar.jpg
https://i.ibb.co/ncm43hC/colddisperse.jpg
https://i.ibb.co/HFnGwW0/colddispersedetergent.jpg
https://i.ibb.co/jwzfjBj/colddispersesalt.jpg
https://i.ibb.co/1GnRH7P/colddispersevinegar.jpg
https://i.ibb.co/12Yq2rT/coldink.jpg
https://i.ibb.co/PzrdTnS/coldinkdetergent.jpg
https://i.ibb.co/pxKNnvL/coldinksalt.jpg
https://i.ibb.co/vdYBNp3/coldinkvinegar.jpg
https://i.ibb.co/SfZ2Q7Q/coldreactive.jpg
https://i.ibb.co/Gx26yn0/coldreactivedetergent.jpg
https://i.ibb.co/b34FCfq/coldreactivesalt.jpg
https://i.ibb.co/Y2C8xJg/coldreactivevinegar.jpg
https://i.ibb.co/ZXz3x8Q/hotacid.jpg
https://i.ibb.co/xgGMt0N/hotaciddetergent.jpg
https://i.ibb.co/Pjxm7GY/hotacidsalt.jpg
https://i.ibb.co/mv4qyvY/hotacidvinegar.jpg
https://i.ibb.co/9hsk5dn/hotdisperse.jpg
https://i.ibb.co/qrB72x9/hotdispersedetergent.jpg
https://i.ibb.co/BZ3kG9L/hotdispersesalt.jpg
https://i.ibb.co/LdqC9n0/hotdispersevinegar.jpg
https://i.ibb.co/LZGyJVf/hotink.jpg
https://i.ibb.co/Tk1DjwY/hotinkdetergent.jpg
https://i.ibb.co/LgZM9TQ/hotinksalt.jpg
https://i.ibb.co/N9h6J25/hotinkvinegar.jpg
https://i.ibb.co/vvF1d5m/hotreactive.jpg
https://i.ibb.co/99WSk0G/hotreactivedetergent.jpg
https://i.ibb.co/sFpn1S2/hotreactivesalt.jpg
https://i.ibb.co/4mSKXGV/hotreactivevinegar.jpghttps://i.ibb.co/WFnGdM6/coldaciddetergent.jpg
https://i.ibb.co/wdWL02y/coldacid.jpg
https://i.ibb.co/NjR1yV0/coldacidsalt.jpg
https://i.ibb.co/SvWZrf9/coldacidvinegar.jpg
https://i.ibb.co/TH0StY5/colddisperse.jpg
https://i.ibb.co/1vnhZdM/colddispersedetergent.jpg
https://i.ibb.co/3MNFYsM/colddispersesalt.jpg
https://i.ibb.co/Yt6mP0V/colddispersevinegar.jpg
https://i.ibb.co/1TJD2gd/coldink.jpg
https://i.ibb.co/nM8qLFH/coldinkdetergent.jpg
https://i.ibb.co/svC5yKK/coldinksalt.jpg
https://i.ibb.co/26cz8WT/coldinkvinegar.jpg
https://i.ibb.co/gPgKhSP/coldreactive.jpg
https://i.ibb.co/QdB4s0B/coldreactivedetergent.jpg
https://i.ibb.co/nrFmPth/coldreactivesalt.jpg
https://i.ibb.co/5vMLpYW/coldreactivevinegar.jpg
https://i.ibb.co/PjSydGL/hotacid.jpg
https://i.ibb.co/HYYkSkJ/hotaciddetergent.jpg
https://i.ibb.co/2Z07sZ5/hotacidsalt.jpg
https://i.ibb.co/9npvz3g/hotacidvinegar.jpg
https://i.ibb.co/hdXZqNM/hotdisperse.jpg
https://i.ibb.co/JzyZ0Fz/hotdispersedetergent.jpg
https://i.ibb.co/DYz66qw/hotdispersesalt.jpg
https://i.ibb.co/Lt6sCrf/hotdispersevinegar.jpg
https://i.ibb.co/PTPPZW1/hotink.jpg
https://i.ibb.co/mJX8Lb5/hotinkdetergent.jpg
https://i.ibb.co/Wc0xw5Z/hotinksalt.jpg
https://i.ibb.co/nC0ywBT/hotinkvinegar.jpg
https://i.ibb.co/rtxV7qJ/hotreactive.jpg
https://i.ibb.co/QjKpFqS/hotreactivedetergent.jpg
https://i.ibb.co/nM3KN6v/hotreactivesalt.jpg
https://i.ibb.co/vJ6QS1h/hotreactivevinegar.jpg
https://i.ibb.co/PG8rNpQ/coldaciddetergent.jpg
https://i.ibb.co/vBzDhcY/coldacid.jpg
https://i.ibb.co/41K0sqh/coldacidsalt.jpg
https://i.ibb.co/hZmqXCX/coldacidvinegar.jpg
https://i.ibb.co/CbV1YX8/colddisperse.jpg
https://i.ibb.co/NxdKWDm/colddispersedetergent.jpg
https://i.ibb.co/x739Dvj/colddispersesalt.jpg
https://i.ibb.co/mF8mmv3/colddispersevinegar.jpg
https://i.ibb.co/L92VM5F/coldink.jpg
https://i.ibb.co/9NjPZqw/coldinkdetergent.jpg
https://i.ibb.co/C5JSL2q/coldinksalt.jpg
https://i.ibb.co/P1gXfFJ/coldinkvinegar.jpg
https://i.ibb.co/QMjXrfy/coldreactive.jpg
https://i.ibb.co/SmGvLjF/coldreactivedetergent.jpg
https://i.ibb.co/rmyQ69p/coldreactivesalt.jpg
https://i.ibb.co/k9trPfj/coldreactivevinegar.jpg
https://i.ibb.co/TKB6Ykt/hotacid.jpg
https://i.ibb.co/Wgf4n9c/hotaciddetergent.jpg
https://i.ibb.co/ZmsBhK8/hotacidsalt.jpg
https://i.ibb.co/MMDrWHQ/hotacidvinegar.jpg
https://i.ibb.co/wL5rWtL/hotdisperse.jpg
https://i.ibb.co/4mV27g9/hotdispersedetergent.jpg
https://i.ibb.co/svTvSSS/hotdispersesalt.jpg
https://i.ibb.co/j5Qmxv8/hotdispersevinegar.jpg
https://i.ibb.co/6Fr74b1/hotink.jpg
https://i.ibb.co/JKLYgNq/hotinkdetergent.jpg
https://i.ibb.co/Nmf5n7h/hotinksalt.jpg
https://i.ibb.co/qpXymp3/hotinkvinegar.jpg
https://i.ibb.co/WK6TRw8/hotreactive.jpg
https://i.ibb.co/Q6XvZ1B/hotreactivedetergent.jpg
https://i.ibb.co/86KWscf/hotreactivesalt.jpg
https://i.ibb.co/Km6xxBt/hotreactivevinegar.jpg
https://i.ibb.co/F0VS8hZ/coldaciddetergent.jpg
https://i.ibb.co/JjHbXLx/coldacid.jpg
https://i.ibb.co/s9vNgy2/coldacidsalt.jpg
https://i.ibb.co/Z25spY5/coldacidvinegar.jpg
https://i.ibb.co/dMFv948/colddisperse.jpg
https://i.ibb.co/r58s9DX/colddispersedetergent.jpg
https://i.ibb.co/wZHzFY6/colddispersesalt.jpg
https://i.ibb.co/Gc1hjsk/colddispersevinegar.jpg
https://i.ibb.co/JvdZJYS/coldink.jpg
https://i.ibb.co/sWQJnPj/coldinkdetergent.jpg
https://i.ibb.co/r5mfFfL/coldinksalt.jpg
https://i.ibb.co/khV3nDV/coldinkvinegar.jpg
https://i.ibb.co/gRTqcCd/coldreactive.jpg
https://i.ibb.co/sbxsG4B/coldreactivedetergent.jpg
https://i.ibb.co/sP4QVHF/coldreactivesalt.jpg
https://i.ibb.co/tZ9nnd6/coldreactivevinegar.jpg
https://i.ibb.co/8K3NMgx/hotacid.jpg
https://i.ibb.co/xD38Jr5/hotaciddetergent.jpg
https://i.ibb.co/vJ1MZBk/hotacidsalt.jpg
https://i.ibb.co/Qr4SFbr/hotacidvinegar.jpg
https://i.ibb.co/FnvV0Wc/hotdisperse.jpg
https://i.ibb.co/8BMHcGT/hotdispersedetergent.jpg
https://i.ibb.co/7RrCMp6/hotdispersesalt.jpg
https://i.ibb.co/56bMvJ1/hotdispersevinegar.jpg
https://i.ibb.co/SQghpTV/hotink.jpg
https://i.ibb.co/t3ZwNYW/hotinkdetergent.jpg
https://i.ibb.co/hB0QD61/hotinksalt.jpg
https://i.ibb.co/ZdCw58h/hotinkvinegar.jpg
https://i.ibb.co/tDKvVt4/hotreactive.jpg
https://i.ibb.co/gZCcZnq/hotreactivedetergent.jpg
https://i.ibb.co/jfyNtkD/hotreactivesalt.jpg
https://i.ibb.co/Yf0t5Hp/hotreactivevinegar.jpg
https://i.ibb.co/DkKnrcR/coldaciddetergent.jpg
https://i.ibb.co/YQRgzdR/coldacid.jpg
https://i.ibb.co/cFxt0VM/coldacidsalt.jpg
https://i.ibb.co/wp61tgf/coldacidvinegar.jpg
https://i.ibb.co/DMN6rLB/colddisperse.jpg
https://i.ibb.co/FzrtyjV/colddispersedetergent.jpg
https://i.ibb.co/5TtN0ZJ/colddispersesalt.jpg
https://i.ibb.co/djknJtJ/colddispersevinegar.jpg
https://i.ibb.co/QbZZRwf/coldink.jpg
https://i.ibb.co/CBgx1fQ/coldinkdetergent.jpg
https://i.ibb.co/j5JNfdz/coldinksalt.jpg
https://i.ibb.co/4mG8nLH/coldinkvinegar.jpg
https://i.ibb.co/Dr0nHsS/coldreactive.jpg
https://i.ibb.co/bvwKDyP/coldreactivedetergent.jpg
https://i.ibb.co/2PSY4tX/coldreactivesalt.jpg
https://i.ibb.co/KLQQy1j/coldreactivevinegar.jpg
https://i.ibb.co/qJP8HCk/hotacid.jpg
https://i.ibb.co/254x8sV/hotaciddetergent.jpg
https://i.ibb.co/hDCJJNq/hotacidsalt.jpg
https://i.ibb.co/NNTTdZ7/hotacidvinegar.jpg
https://i.ibb.co/tpQnypP/hotdisperse.jpg
https://i.ibb.co/YRpXk41/hotdispersedetergent.jpg
https://i.ibb.co/nmZW46r/hotdispersesalt.jpg
https://i.ibb.co/pXXn0Xv/hotdispersevinegar.jpg
https://i.ibb.co/hM5365N/hotink.jpg
https://i.ibb.co/VmqxY10/hotinkdetergent.jpg
https://i.ibb.co/pzLQ4db/hotinksalt.jpg
https://i.ibb.co/nQZ2j52/hotinkvinegar.jpg
https://i.ibb.co/HVFYDpM/hotreactive.jpg
https://i.ibb.co/BsftgHz/hotreactivedetergent.jpg
https://i.ibb.co/k5fDL93/hotreactivesalt.jpg
https://i.ibb.co/hWFfM63/hotreactivevinegar.jpg
https://i.ibb.co/rx0mH90/coldaciddetergent.jpg
https://i.ibb.co/NCkkK5r/coldacid.jpg
https://i.ibb.co/rttGrjc/coldacidsalt.jpg
https://i.ibb.co/KNDKD5k/coldacidvinegar.jpg
https://i.ibb.co/yypjLLr/colddisperse.jpg
https://i.ibb.co/qYXrR5B/colddispersedetergent.jpg
https://i.ibb.co/jGmVBSH/colddispersesalt.jpg
https://i.ibb.co/XsPpRyX/colddispersevinegar.jpg
https://i.ibb.co/ByHDbYg/coldink.jpg
https://i.ibb.co/5jXrpLn/coldinkdetergent.jpg
https://i.ibb.co/wRBTMy7/coldinksalt.jpg
https://i.ibb.co/HNRLhtQ/coldinkvinegar.jpg
https://i.ibb.co/hB1G25m/coldreactive.jpg
https://i.ibb.co/8YNgm5h/coldreactivedetergent.jpg
https://i.ibb.co/C1XrvKF/coldreactivesalt.jpg
https://i.ibb.co/S7wPs09/coldreactivevinegar.jpg
https://i.ibb.co/1fBfTR9/hotacid.jpg
https://i.ibb.co/bK2r5dF/hotaciddetergent.jpg
https://i.ibb.co/5MCdRFz/hotacidsalt.jpg
https://i.ibb.co/djLQQNr/hotacidvinegar.jpg
https://i.ibb.co/9WDrsdK/hotdisperse.jpg
https://i.ibb.co/cD1bw7F/hotdispersedetergent.jpg
https://i.ibb.co/tbb1VWp/hotdispersesalt.jpg
https://i.ibb.co/bFKQf6R/hotdispersevinegar.jpg
https://i.ibb.co/d0m6FG2/hotink.jpg
https://i.ibb.co/ScXN8YX/hotinkdetergent.jpg
https://i.ibb.co/yPtq7Kf/hotinksalt.jpg
https://i.ibb.co/wMj1th6/hotinkvinegar.jpg
https://i.ibb.co/25jYKdc/hotreactive.jpg
https://i.ibb.co/z2W5XkF/hotreactivedetergent.jpg
https://i.ibb.co/WKJryfh/hotreactivesalt.jpg
https://i.ibb.co/zhQcYN9/hotreactivevinegar.jpg
https://i.ibb.co/f1qjNbL/coldaciddetergent.jpg
https://i.ibb.co/MGqjKpv/coldacid.jpg
https://i.ibb.co/wpS5dkd/coldacidsalt.jpg
https://i.ibb.co/GtZfzbW/coldacidvinegar.jpg
https://i.ibb.co/MSCfkN1/colddisperse.jpg
https://i.ibb.co/H2PVVV5/colddispersedetergent.jpg
https://i.ibb.co/tQXL674/colddispersevinegar.jpg
https://i.ibb.co/ZLnFWrR/coldink.jpg
https://i.ibb.co/k1wwWL2/coldinkdetergent.jpg
https://i.ibb.co/C8jcsxC/coldinksalt.jpg
https://i.ibb.co/jbJ4wSX/coldinkvinegar.jpg
https://i.ibb.co/R6s7Kv0/coldispersesalt.jpg
https://i.ibb.co/c6MNCvB/coldreactive.jpg
https://i.ibb.co/HtcFBnF/coldreactivedetergent.jpg
https://i.ibb.co/2yW8DVR/coldreactivesalt.jpg
https://i.ibb.co/Wn1qkH4/coldreactivevinegar.jpg
https://i.ibb.co/hHSxZMj/hotacid.jpg
https://i.ibb.co/4fm672b/hotaciddetergent.jpg
https://i.ibb.co/B4L88dZ/hotacidsalt.jpg
https://i.ibb.co/PN2Tbcf/hotacidvinegar.jpg
https://i.ibb.co/Nt2kcn7/hotdisperse.jpg
https://i.ibb.co/T4sztZM/hotdispersedetergent.jpg
https://i.ibb.co/WzcmvNH/hotdispersesalt.jpg
https://i.ibb.co/jGrM6st/hotdispersevinegar.jpg
https://i.ibb.co/DDhphCx/hotink.jpg
https://i.ibb.co/NFBr80q/hotinkdetergent.jpg
https://i.ibb.co/qxMxVh5/hotinksalt.jpg
https://i.ibb.co/RYy6Cjc/hotinkvinegar.jpg
https://i.ibb.co/N1cKnwz/hotreactive.jpg
https://i.ibb.co/ky8K9k6/hotreactivedetergent.jpg
https://i.ibb.co/8Kj3VVF/hotreactivesalt.jpg
https://i.ibb.co/Y3Hyq9m/hotreactivevinegar.jpg
https://i.ibb.co/PWhRv42/coldacid.jpg
https://i.ibb.co/LP67CHN/coldaciddetergent.jpg
https://i.ibb.co/FYnrQnK/coldacidsalt.jpg
https://i.ibb.co/CwxCKhd/coldacidvinegar.jpg
https://i.ibb.co/ncm43hC/colddisperse.jpg
https://i.ibb.co/HFnGwW0/colddispersedetergent.jpg
https://i.ibb.co/jwzfjBj/colddispersesalt.jpg
https://i.ibb.co/1GnRH7P/colddispersevinegar.jpg
https://i.ibb.co/12Yq2rT/coldink.jpg
https://i.ibb.co/PzrdTnS/coldinkdetergent.jpg
https://i.ibb.co/pxKNnvL/coldinksalt.jpg
https://i.ibb.co/vdYBNp3/coldinkvinegar.jpg
https://i.ibb.co/SfZ2Q7Q/coldreactive.jpg
https://i.ibb.co/Gx26yn0/coldreactivedetergent.jpg
https://i.ibb.co/b34FCfq/coldreactivesalt.jpg
https://i.ibb.co/Y2C8xJg/coldreactivevinegar.jpg
https://i.ibb.co/ZXz3x8Q/hotacid.jpg
https://i.ibb.co/xgGMt0N/hotaciddetergent.jpg
https://i.ibb.co/Pjxm7GY/hotacidsalt.jpg
https://i.ibb.co/mv4qyvY/hotacidvinegar.jpg
https://i.ibb.co/9hsk5dn/hotdisperse.jpg
https://i.ibb.co/qrB72x9/hotdispersedetergent.jpg
https://i.ibb.co/BZ3kG9L/hotdispersesalt.jpg
https://i.ibb.co/LdqC9n0/hotdispersevinegar.jpg
https://i.ibb.co/LZGyJVf/hotink.jpg
https://i.ibb.co/Tk1DjwY/hotinkdetergent.jpg
https://i.ibb.co/LgZM9TQ/hotinksalt.jpg
https://i.ibb.co/N9h6J25/hotinkvinegar.jpg
https://i.ibb.co/vvF1d5m/hotreactive.jpg
https://i.ibb.co/99WSk0G/hotreactivedetergent.jpg
https://i.ibb.co/sFpn1S2/hotreactivesalt.jpg
https://i.ibb.co/4mSKXGV/hotreactivevinegar.jpg"

OBJECTS=()

for file in ${FILES[@]}; do
    #echo "$file"
    #NAME=$(echo "$file" | cut -c 16- | tr -d ".JPG" )
    NAME=$(echo "$file" | cut -c 26- | tr -d ".JPG" )
    #echo $NAME
    obj="$(jo src=$file title=$NAME)"
    #echo $obj
    OBJECTS+=($obj)
done

CMD=""

for obj in ${OBJECTS[@]}; do
    CMD="$CMD $obj"
    #echo $obj
done

jo -p -a $CMD

